[package]
name = "nats-io"
version = "0.1.0"
authors = ["takuto <takuto.yoshikai@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
